apiVersion: apps/v1
kind: Deployment
metadata:
  name: discourse-web
  namespace: discourse
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: discourse
          env:
            - name: MIGRATE_ON_BOOT
              value: "1"
            - name: PRECOMPILE_ON_BOOT
              value: "1"
